-- script para cargar glc en fnc

DROP TABLE IF EXISTS GLC_en_FNC;
DROP TABLE IF EXISTS matriz_cyk;
DROP TABLE IF EXISTS expresion_json;

CREATE TABLE GLC_en_FNC(
	start BOOLEAN,
	parte_izq TEXT,
	parte_der1 TEXT,
	parte_der2 TEXT,
	tipo_produccion SMALLINT
);

CREATE TABLE matriz_cyk(
	i SMALLINT,
	j SMALLINT,
	x TEXT[]
);

CREATE TABLE expresion_json(
	string TEXT
);

INSERT INTO GLC_en_FNC VALUES (FALSE, 'L_ABRE', '{', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'L_CIERRA', '}', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'CONT_LCIERRA', 'CONTENIDO', 'L_CIERRA', 2);
INSERT INTO GLC_en_FNC VALUES (TRUE, 'S', 'L_ABRE', 'CONT_LCIERRA', 2);
INSERT INTO GLC_en_FNC VALUES (TRUE, 'S', 'L_ABRE', 'L_CIERRA', 2);

INSERT INTO GLC_en_FNC VALUES (FALSE, 'COMILLA', '"', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'DOS_PUNTOS', ':', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'COMA', ',', NULL, 1);

INSERT INTO GLC_en_FNC VALUES (FALSE, 'STR_CIERRE', 'STRING', 'COMILLA', 2);     
INSERT INTO GLC_en_FNC VALUES (FALSE, 'CLAVE', 'COMILLA', 'STR_CIERRE', 2);       

INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', 'DIGITO', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', 'DIGITO', 'NUM', 2);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', 'COMILLA', 'STR_CIERRE', 2);   
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', 'L_ABRE', 'L_CIERRA', 2);                   
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', 'L_ABRE', 'CONT_LCIERRA', 2);                   

INSERT INTO GLC_en_FNC VALUES (FALSE, 'PUNTOS_VALOR', 'DOS_PUNTOS', 'VALOR', 2);  
INSERT INTO GLC_en_FNC VALUES (FALSE, 'CLAVE_VALOR', 'CLAVE', 'PUNTOS_VALOR', 2); 

INSERT INTO GLC_en_FNC VALUES (FALSE, 'CONTENIDO', 'CLAVE', 'PUNTOS_VALOR', 2);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'COMA_CONTENIDO', 'COMA', 'CONTENIDO', 2);  
INSERT INTO GLC_en_FNC VALUES (FALSE, 'CONTENIDO', 'CLAVE_VALOR', 'COMA_CONTENIDO', 2); 

INSERT INTO GLC_en_FNC VALUES (FALSE, 'NUM', 'digito', 'NUM', 2);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'NUM', 'digito', NULL, 1);

INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'letra', 'STRING', 2);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'letra', NULL, 1);

INSERT INTO GLC_en_FNC (start, parte_izq, parte_der1, parte_der2, tipo_produccion)
SELECT false, 'digito', CAST(i AS text), '', 1 FROM generate_series(0, 9) AS i;

