-- script para cargar glc en fnc

DROP TABLE IF EXISTS GLC_en_FNC;
DROP TABLE IF EXISTS matriz_cyk;
DROP TABLE IF EXISTS expresion_json;

CREATE TABLE GLC_en_FNC(
	start BOOLEAN,
	parte_izq TEXT,
	parte_der1 TEXT,
	parte_der2 TEXT,
	tipo_produccion SMALLINT
);

CREATE TABLE matriz_cyk(
	i SMALLINT,
	j SMALLINT,
	x TEXT[]
);

CREATE TABLE expresion_json(
--	id SERIAL PRIMARY KEY,
	string TEXT
);

INSERT INTO GLC_en_FNC VALUES (FALSE, 'L_ABRE', '{', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'L_CIERRA', '}', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (TRUE, 'S', 'L_ABRE', 'L_CIERRA', 2);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'CONT_LCIERRA', 'CONTENIDO', 'L_CIERRA', 2);
INSERT INTO GLC_en_FNC VALUES (TRUE, 'S', 'L_ABRE', 'CONT_LCIERRA', 2);

INSERT INTO GLC_en_FNC VALUES (FALSE, 'COMA', ',', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'CL_COMA', 'CLAVE_VALOR', 'COMA', 2);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'CONTENIDO', 'CL_COMA', 'CONTENIDO', 2);

INSERT INTO GLC_en_FNC VALUES (FALSE, 'COMILLAS', '”', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'DOBLE_PUNTO', ':', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'COMILLA_STR', 'COMILLAS', 'STRING', 2);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'COM_STR_COM', 'COMILLA_STR', 'COMILLAS', 2);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'COMILLA_STR_DP', 'COM_STR_COM', 'DOBLE_PUNTO', 2);

INSERT INTO GLC_en_FNC VALUES (FALSE, 'CONTENIDO', 'COMILLA_STR_DP', 'VALOR', 2);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'CLAVE_VALOR', 'COMILLA_STR_DP', 'VALOR', 2);

INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', 'DIGITO', 'NUM', 2);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', 'L_ABRE', 'L_CIERRA', 2);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', 'L_ABRE', 'CONT_LCIERRA', 2);

INSERT INTO GLC_en_FNC VALUES (FALSE, 'COMILLA_SIMPLE', '’', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'CS_STRING', 'COMILLA_SIMPLE', 'STRING', 2);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', 'CS_STRING', 'COMILLA_SIMPLE', 2);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', 'COMILLA_SIMPLE', 'COMILLA_SIMPLE', 2);

INSERT INTO GLC_en_FNC VALUES (FALSE, 'NUM', 'DIGITO', 'NUM', 2);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'LETRA', 'STRING', 2);

-- =======================================================
-- Dígitos 0-9
-- =======================================================
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', '0', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', '1', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', '2', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', '3', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', '4', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', '5', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', '6', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', '7', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', '8', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'VALOR', '9', NULL, 1);

INSERT INTO GLC_en_FNC VALUES (FALSE, 'NUM', '0', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'NUM', '1', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'NUM', '2', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'NUM', '3', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'NUM', '4', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'NUM', '5', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'NUM', '6', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'NUM', '7', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'NUM', '8', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'NUM', '9', NULL, 1);

INSERT INTO GLC_en_FNC VALUES (FALSE, 'DIGITO', '0', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'DIGITO', '1', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'DIGITO', '2', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'DIGITO', '3', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'DIGITO', '4', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'DIGITO', '5', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'DIGITO', '6', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'DIGITO', '7', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'DIGITO', '8', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'DIGITO', '9', NULL, 1);

-- =======================================================
-- Letras a-z
-- =======================================================
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'a', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'b', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'c', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'd', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'e', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'f', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'g', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'h', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'i', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'j', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'k', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'l', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'm', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'n', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'o', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'p', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'q', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'r', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 's', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 't', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'u', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'v', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'w', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'x', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'y', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'STRING', 'z', NULL, 1);

INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'a', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'b', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'c', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'd', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'e', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'f', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'g', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'h', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'i', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'j', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'k', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'l', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'm', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'n', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'o', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'p', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'q', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'r', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 's', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 't', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'u', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'v', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'w', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'x', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'y', NULL, 1);
INSERT INTO GLC_en_FNC VALUES (FALSE, 'LETRA', 'z', NULL, 1);

